package br.com.devedores.app;
import java.text.SimpleDateFormat;
import android.app.*;import android.os.*;import android.graphics.Color;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;
public class CalendarActivity extends Activity{
 DataStore ds;LinearLayout root;long selected;
 public void onCreate(Bundle b){super.onCreate(b);ds=new DataStore(this);selected=System.currentTimeMillis();build();}
 String money(double x){return String.format(Locale.getDefault(),"R$ %.2f",x);}
 void build(){root=Ui.col(this);ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setVerticalScrollBarEnabled(false);sc.addView(root);setContentView(sc);Ui.applySystemBars(this,root);LinearLayout top=Ui.row(this);Button back=Ui.btnDark(this,"‹ Voltar");back.setOnClickListener(v->finish());top.addView(back,new LinearLayout.LayoutParams(Ui.dp(this,82),Ui.dp(this,46)));LinearLayout tt=Ui.col(this);tt.setPadding(Ui.dp(this,10),0,0,0);tt.addView(Ui.title(this,"Calendário",23));tt.addView(Ui.label(this,"Vencimentos e lembretes"));top.addView(tt,new LinearLayout.LayoutParams(0,Ui.dp(this,54),1));root.addView(top);Ui.gap(this,root,12);CalendarView cal=new CalendarView(this);cal.setDate(selected,false,true);cal.setOnDateChangeListener((v,y,m,d)->{Calendar c=Calendar.getInstance();c.set(y,m,d,0,0,0);c.set(Calendar.MILLISECOND,0);selected=c.getTimeInMillis();render(c);});root.addView(Ui.card(this));((LinearLayout)root.getChildAt(root.getChildCount()-1)).addView(cal,new LinearLayout.LayoutParams(-1,Ui.dp(this,320)));render(Calendar.getInstance());}
 void render(Calendar day){while(root.getChildCount()>4)root.removeViewAt(4);String key=new SimpleDateFormat("dd/MM/yyyy",Locale.getDefault()).format(day.getTime());root.addView(Ui.eyebrow(this,"EVENTOS EM "+key));boolean any=false;for(Models.Client c:ds.clients)for(Models.Loan l:c.loans)for(int i=0;i<l.installments;i++){long d=l.dueAt(i);String dk=new SimpleDateFormat("dd/MM/yyyy",Locale.getDefault()).format(new Date(d));if(key.equals(dk)){any=true;boolean paid=l.installmentPaid(i),late=!paid&&d<System.currentTimeMillis();int accent=paid?Ui.GREEN:late?Ui.RED:Ui.GOLD;LinearLayout card=Ui.card(this);LinearLayout h=Ui.row(this);h.addView(Ui.title(this,c.name,16),new LinearLayout.LayoutParams(0,Ui.dp(this,30),1));h.addView(Ui.pill(this,paid?"Paga":late?"Atrasada":"Pendente",accent,Color.WHITE));card.addView(h);card.addView(Ui.text(this,l.title+"  •  parcela "+(i+1)+"\n"+money(l.installmentAmount)+"  •  "+new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date(d)),14));root.addView(card);Ui.gap(this,root,6);}}for(Models.Reminder r:ds.reminders){String rk=new SimpleDateFormat("dd/MM/yyyy",Locale.getDefault()).format(new Date(r.when));if(key.equals(rk)){any=true;LinearLayout card=Ui.softCard(this,Ui.BLUE);card.addView(Ui.title(this,"🔔 "+r.title,15));card.addView(Ui.text(this,r.details,13));root.addView(card);Ui.gap(this,root,6);}}if(!any)root.addView(Ui.label(this,"Nenhum evento neste dia."));}
}
