package br.com.devedores.app;

import android.app.*;
import android.content.*;
import android.os.Bundle;
import android.widget.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class LoanActivity extends Activity {
    DataStore ds; Models.Client client; Models.Loan loan; LinearLayout root;
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Ui.BG);getWindow().setNavigationBarColor(Ui.BG);ds=new DataStore(this);load();}
    void load(){client=ds.client(getIntent().getStringExtra("clientId"));loan=ds.loan(getIntent().getStringExtra("loanId"));if(loan==null||client==null){finish();return;}build();}
    @Override protected void onResume(){super.onResume();if(ds!=null){ds.load();client=ds.client(getIntent().getStringExtra("clientId"));loan=ds.loan(getIntent().getStringExtra("loanId"));if(loan!=null&&client!=null)build();}}
    String money(double x){return String.format(Locale.getDefault(),"R$ %.2f",x);}
    String date(long t){return new SimpleDateFormat("dd/MM/yyyy 'às' HH:mm",new Locale("pt","BR")).format(new Date(t));}

    void build(){
        root=Ui.col(this);ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setVerticalScrollBarEnabled(false);sc.addView(root);setContentView(sc); Ui.applySystemBars(this, root);
        LinearLayout top=Ui.row(this);Button back=Ui.btnDark(this,"‹  Voltar");back.setOnClickListener(v->finish());top.addView(back,new LinearLayout.LayoutParams(Ui.dp(this,88),Ui.dp(this,44)));LinearLayout tt=Ui.col(this);tt.setPadding(Ui.dp(this,10),0,0,0);tt.addView(Ui.title(this,loan.title,21));tt.addView(Ui.label(this,"Contrato • "+client.name));top.addView(tt,new LinearLayout.LayoutParams(0,Ui.dp(this,52),1));Button more=Ui.btnDark(this,"•••");more.setOnClickListener(v->loanMenu());top.addView(more,new LinearLayout.LayoutParams(Ui.dp(this,54),Ui.dp(this,44)));root.addView(top);Ui.gap(this,root,14);

        double pct=loan.total<=0?0:loan.paid()/loan.total*100d;boolean quitado=loan.balance()<=0.005;int overdue=0;double overdueVal=0;for(int i=0;i<loan.installments;i++)if(!loan.installmentPaid(i)&&loan.dueAt(i)<System.currentTimeMillis()){overdue++;overdueVal+=Math.max(0,loan.installmentAmount-loan.paidForInstallment(i));}
        LinearLayout hero=Ui.heroCard(this,overdue>0?Ui.RED:(quitado?Ui.GREEN:Ui.GOLD));hero.addView(Ui.eyebrow(this,overdue>0?"CONTRATO EM ATRASO":quitado?"CONTRATO QUITADO":"CONTRATO ATIVO"));hero.addView(Ui.title(this,money(loan.balance()),30));hero.addView(Ui.label(this,"saldo de um total de "+money(loan.total)));Ui.gap(this,hero,8);hero.addView(Ui.progress(this,(int)Math.min(100,pct),100),new LinearLayout.LayoutParams(-1,Ui.dp(this,8)));Ui.gap(this,hero,4);hero.addView(Ui.label(this,String.format(Locale.getDefault(),"%.0f%% recebido • %d/%d parcelas quitadas",pct,countPaid(),loan.installments)));if(overdue>0){Ui.gap(this,hero,5);hero.addView(Ui.pill(this,overdue+" parcela(s) atrasada(s) • "+money(overdueVal),Ui.RED,Ui.WHITE));}root.addView(hero);Ui.gap(this,root,10);

        LinearLayout r1=Ui.row(this);r1.addView(Ui.statCard(this,"EMPRESTADO",money(loan.principal),Ui.GOLD),new LinearLayout.LayoutParams(0,Ui.dp(this,86),1));Ui.gap(this,r1,6);r1.addView(Ui.statCard(this,"JUROS",money(loan.interestValue),Ui.RED),new LinearLayout.LayoutParams(0,Ui.dp(this,86),1));root.addView(r1);Ui.gap(this,root,7);
        LinearLayout r2=Ui.row(this);r2.addView(Ui.statCard(this,"RECEBIDO",money(loan.paid()),Ui.GREEN),new LinearLayout.LayoutParams(0,Ui.dp(this,86),1));Ui.gap(this,r2,6);r2.addView(Ui.statCard(this,"PARCELA",money(loan.installmentAmount),Ui.BLUE),new LinearLayout.LayoutParams(0,Ui.dp(this,86),1));root.addView(r2);Ui.gap(this,root,12);

        LinearLayout contract=Ui.softCard(this,Ui.BLUE);contract.addView(Ui.eyebrow(this,"CONDIÇÕES"));String interestLabel="FIXO • "+money(loan.interestValue);if("PERCENT".equals(loan.interestMode))interestLabel=String.format(Locale.getDefault(),"%.2f%% • %s",loan.interestPercent,money(loan.interestValue));contract.addView(Ui.text(this,interestLabel+"  •  "+loan.frequency+"  •  "+loan.installments+" parcelas",14));contract.addView(Ui.label(this,"Primeiro vencimento: "+date(loan.firstDue)));root.addView(contract);Ui.gap(this,root,12);

        LinearLayout act=Ui.row(this);Button pay=Ui.btn(this,"Registrar recebimento");pay.setOnClickListener(v->pay());Button note=Ui.btnDark(this,"Observações");note.setOnClickListener(v->editNotes());act.addView(pay,new LinearLayout.LayoutParams(0,Ui.dp(this,48),1));Ui.gap(this,act,6);act.addView(note,new LinearLayout.LayoutParams(0,Ui.dp(this,48),1));root.addView(act);Ui.gap(this,root,16);

        root.addView(Ui.sectionTitle(this,"Parcelas"));Ui.gap(this,root,4);
        for(int i=0;i<loan.installments;i++){double pg=loan.paidForInstallment(i),rest=Math.max(0,loan.installmentAmount-pg);long due=loan.dueAt(i);boolean paid=loan.installmentPaid(i),late=!paid&&due<System.currentTimeMillis();int accent=paid?Ui.GREEN:late?Ui.RED:Ui.GOLD;String st=paid?"Paga":late?"Atrasada":(pg>0?"Parcial":"Pendente");LinearLayout card=Ui.card(this);LinearLayout h=Ui.row(this);h.addView(Ui.title(this,"Parcela "+(i+1),16),new LinearLayout.LayoutParams(0,Ui.dp(this,30),1));h.addView(Ui.pill(this,st,accent,Ui.WHITE));card.addView(h);card.addView(Ui.label(this,date(due)));Ui.gap(this,card,4);card.addView(Ui.progress(this,(int)(loan.installmentAmount<=0?0:pg/loan.installmentAmount*100d),100),new LinearLayout.LayoutParams(-1,Ui.dp(this,7)));Ui.gap(this,card,4);card.addView(Ui.text(this,"Recebido "+money(pg)+"  •  restante "+money(rest),13));Button rs=Ui.btnDark(this,"Alterar data e horário");final int idx=i;rs.setOnClickListener(v->reschedule(idx));card.addView(rs,new LinearLayout.LayoutParams(-1,Ui.dp(this,42)));root.addView(card);Ui.gap(this,root,7);}

        root.addView(Ui.sectionTitle(this,"Histórico"));Ui.gap(this,root,4);if(loan.payments.isEmpty())root.addView(Ui.label(this,"Nenhum pagamento registrado ainda."));for(Models.Payment p:loan.payments){LinearLayout card=Ui.card(this);LinearLayout r=Ui.row(this);r.addView(Ui.iconBadge(this,"✓"),new LinearLayout.LayoutParams(Ui.dp(this,38),Ui.dp(this,38)));LinearLayout tx=Ui.col(this);tx.setPadding(Ui.dp(this,9),0,0,0);tx.addView(Ui.title(this,money(p.amount),14));tx.addView(Ui.label(this,date(p.date)));if(p.note!=null&&!p.note.isEmpty())tx.addView(Ui.label(this,p.note));r.addView(tx,new LinearLayout.LayoutParams(0,Ui.dp(this,56),1));card.addView(r);root.addView(card);Ui.gap(this,root,6);}
        if(!loan.notes.isEmpty()){Ui.gap(this,root,8);LinearLayout n=Ui.softCard(this,Ui.PURPLE);n.addView(Ui.eyebrow(this,"OBSERVAÇÕES"));n.addView(Ui.text(this,loan.notes,14));root.addView(n);}
    }

    int countPaid(){int x=0;for(int i=0;i<loan.installments;i++)if(loan.installmentPaid(i))x++;return x;}

    void pay(){if(loan.balance()<=0){Toast.makeText(this,"Este contrato já foi quitado.",Toast.LENGTH_SHORT).show();return;}LinearLayout p=Ui.col(this);p.setPadding(0,0,0,0);EditText e=Ui.field(this,"Valor recebido (R$)");e.setText(String.valueOf(loan.installmentAmount));EditText n=Ui.field(this,"Observação do recebimento (opcional)");p.addView(e);Ui.gap(this,p,7);p.addView(n);new AlertDialog.Builder(this).setTitle("Registrar recebimento").setView(p).setPositiveButton("Confirmar",(d,w)->{try{double a=parseMoney(e.getText().toString());if(a<=0)throw new Exception();Models.Payment x=new Models.Payment();x.amount=Math.min(a,loan.balance());x.date=System.currentTimeMillis();x.note=n.getText().toString();loan.payments.add(x);ds.save();AlarmScheduler.cancelLoanAlarms(this,loan.id,loan.installments);AlarmScheduler.scheduleAllInstallments(this,client,loan);build();Toast.makeText(this,"Recebimento salvo",Toast.LENGTH_SHORT).show();}catch(Exception ex){Toast.makeText(this,"Informe um valor válido.",Toast.LENGTH_SHORT).show();}}).setNegativeButton("Cancelar",null).show();}
    void reschedule(int index){Calendar c=Calendar.getInstance();c.setTimeInMillis(loan.dueAt(index));new DatePickerDialog(this,(v,y,m,d)->{Calendar x=Calendar.getInstance();x.set(y,m,d);new TimePickerDialog(this,(tv,h,min)->{x.set(Calendar.HOUR_OF_DAY,h);x.set(Calendar.MINUTE,min);x.set(Calendar.SECOND,0);x.set(Calendar.MILLISECOND,0);long delta=x.getTimeInMillis()-loan.dueAt(index);loan.firstDue+=delta;ds.save();AlarmScheduler.cancelLoanAlarms(this,loan.id,loan.installments);AlarmScheduler.scheduleAllInstallments(this,client,loan);build();},c.get(Calendar.HOUR_OF_DAY),c.get(Calendar.MINUTE),true).show();},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show();}
    void editNotes(){EditText e=Ui.field(this,"Observações do contrato");e.setText(loan.notes);new AlertDialog.Builder(this).setTitle("Observações").setView(e).setPositiveButton("Salvar",(d,w)->{loan.notes=e.getText().toString();ds.save();build();}).setNegativeButton("Cancelar",null).show();}
    double parseMoney(String s){String x=s.replace("R$","").trim();if(x.contains(","))x=x.replace(".","").replace(",",".");return Double.parseDouble(x);}
    void loanMenu(){new AlertDialog.Builder(this).setTitle("Ações do contrato").setItems(new String[]{"Editar observações","Reagendar primeira parcela","Excluir contrato"},(d,w)->{if(w==0)editNotes();else if(w==1)reschedule(0);else confirmDelete();}).show();}
    void confirmDelete(){new AlertDialog.Builder(this).setTitle("Excluir contrato?").setMessage("Todas as parcelas e pagamentos deste contrato serão removidos.").setPositiveButton("Excluir",(d,w)->{AlarmScheduler.cancelLoanAlarms(this,loan.id,loan.installments);client.loans.remove(loan);ds.save();finish();}).setNegativeButton("Cancelar",null).show();}
}
